% Set default general parameters for the test.
function test_params = setdefaulttestparams(test_params)

% Create default parameters.
default_params = struct(...
    'verbosity',2,...
    'example_restarts',1,...
    'test_restarts',1,...
    'example_optimal',0,...
    'example_recompute_optimal',0,...
    'test_optimal',0,...
    'cells_state',20,...
    'cells_action',10,...
    'action_quad',0,...
    'test_samples',32,...
    'training_samples',32,...
    'training_sample_lengths',100);

% Set parameters.
test_params = filldefaultparams(test_params,default_params);
