% Fill in default parameters for the objectworld example.
function mdp_params = obstacle_defaultparams(mdp_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'size',10,...
    'sensors',2,...
    'motors',2,...
    'objects',40,...
    'c1_1prob',0.1,...
    'c1_2prob',0.2,...
    'c1',6,...
    'c2',6,...
    'rbf_features',1,...
    'fixed_pattern',1,...
    'feature_type','grid',...
    'grid_feature_steps',5,...
    'grid_feature_start',0.1,...
    'grid_feature_step',0.2,...
    'step_cost',40.0,...
    'feature_radius',1.0);

% Set parameters.
mdp_params = filldefaultparams(mdp_params,default_params);
